package net.scarletontv.saxophone.mixin.client;

import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.gui.hud.DebugHud;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.text.Text;
import net.scarletontv.saxophone.index.ModStatusEffects;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(DebugHud.class)
public abstract class DebugHudMixin {
    @Inject(method = "drawLeftText", at = @At("HEAD"), cancellable = true)
    private void drawNewTextLeft(DrawContext context, CallbackInfo ci) {
        PlayerEntity player = MinecraftClient.getInstance().player;

        if (player != null) {
            if (player.hasStatusEffect(ModStatusEffects.UNRAVELING)) {
                ci.cancel();
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 1, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 5, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 10, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 15, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 20, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 25, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 30, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 35, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 40, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 45, 0xFF00FF);
                context.drawTextWithShadow(MinecraftClient.getInstance().textRenderer, Text.literal("ABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVEABSOLVE"), 1, 50, 0xFF00FF);
            }
        }
    }

    @Inject(method = "drawRightText", at = @At("HEAD"), cancellable = true)
    private void drawNewLeftText(DrawContext context, CallbackInfo ci) {
        PlayerEntity player = MinecraftClient.getInstance().player;
        if (player != null) {
            if (player.hasStatusEffect(ModStatusEffects.UNRAVELING)) {
                ci.cancel();
            }
        }
    }
}
